clone_depth: 1
#init:
#    - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

image: Visual Studio 2019

environment:
    BUILD_NO: $(APPVEYOR_BUILD_NUMBER)
    BRANCH: $(APPVEYOR_REPO_BRANCH)
    REPO: $(APPVEYOR_REPO_NAME)
    matrix:
        - ARCH: x86_64
          ARCH_BIT: 64
          APPVEYOR_BUILD_WORKER_IMAGE: macos
          BUILD_DEPS_CMD: "/Users/appveyor/projects/scopy/CI/appveyor/install_macos_deps.sh"
          BUILD_CMD: "/Users/appveyor/projects/scopy/CI/appveyor/build_appveyor_macos.sh"
          PACKAGE_CMD: "/Users/appveyor/projects/scopy/CI/appveyor/package_darwin.sh"
          DEPLOY_FILE: "/Users/appveyor/projects/scopy/build/Scopy.dmg"
          C_COMPILER: -DCMAKE_C_COMPILER=/usr/bin/gcc
          CXX_COMPILER: -DCMAKE_CXX_COMPILER=/usr/bin/g++

install:
    # Install Inno Setup
    - cmd: choco install InnoSetup

build_script:
    - cmd: C:\msys64\usr\bin\bash -lc "/c/projects/scopy/CI/appveyor/extract_msys_deps.sh"
    - cmd: C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Syu"
    - cmd: set PATH=%PATH%;"C:\Program Files (x86)\Inno Setup 6"
    - cmd: "%BUILD_DEPS_CMD%"

    - sh: echo $BUILD_DEPS_CMD
    - sh: $BUILD_DEPS_CMD
    - sh: $BUILD_CMD
    - sh: $PACKAGE_CMD

    - echo "### Push artifacts ... "
    - sh: if [[ $DEPLOY_FILE != "" ]]; then appveyor PushArtifact $DEPLOY_FILE; fi

#on_finish:
#    - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
